POST http://localhost:3003/user/signup
Content-Type: application/json

{
	"name": "Teste",
	"email": "teste@teste.com",
	"password": "1234567"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
	"email": "diandrey@teste.com",
	"password": "1234567"
}